= eXtenderZ
François Lamboley <francois.lamboley@happn.com>

:happn: https://happn.com
:frizlab: https://github.com/Frizlab

image:https://img.shields.io/badge/platform-macOS%20|%20iOS%20|%20tvOS%20|%20watchOS-lightgrey.svg?style=flat[Platforms] link:https://swift.org/package-manager/[image:https://img.shields.io/badge/SPM-compatible-E05C43.svg?style=flat[SPM Compatible]] link:License.txt[image:https://img.shields.io/github/license/happn-tech/eXtenderZ.svg[License]] link:{happn}[image:https://img.shields.io/badge/from-happn-0087B4.svg?style=flat[happn]]

TODO

== Installation
Even though there is no Package.swift file in this project in the main branch, the project is now SPM-compatible,
with support for a dynamic and a static version of the package.

*⚠️ Important*: If you use the static version of the package, you *must* add the `-ObjC` flag in _Other Linker Flags_
(`OTHER_LDFLAGS`) in the build settings of your project.

Compatibility is provided via an `xcframework` only. Source SPM-compatibility cannot be provided
AFAICT because the project has a part which does not use ARC, and has a custom modulemap.

Carthage installation should work too for dynamic frameworks, but it hasn’t been tested.

== Versioning Note
The pbxproj sets `DYLIB_CURRENT_VERSION` and `DYLIB_COMPATIBILITY_VERSION` to `$(MARKETING_VERSION)`.
We set the same versions in both fields because this lib is not meant to be shared between processes,
so we don’t really care about the versions.

== Credits
This project was originally created by {frizlab}[François Lamboley] while working at {happn}[happn].
