= eXtenderZ
François Lamboley <francois.lamboley@happn.com>

:happn: https://happn.com
:frizlab: https://github.com/Frizlab

image:https://img.shields.io/badge/platform-macOS%20|%20iOS%20|%20tvOS%20|%20watchOS-lightgrey.svg?style=flat[Platforms] link:https://swift.org/package-manager/[image:https://img.shields.io/badge/SPM-compatible-E05C43.svg?style=flat[SPM Compatible]] link:License.txt[image:https://img.shields.io/github/license/happn-app/eXtenderZ.svg[License]] link:{happn}[image:https://img.shields.io/badge/from-happn-0087B4.svg?style=flat[happn]]

Use the full-extent of Objective-C'`s runtime dynamicity.

== What is this?
TODO

== Installation
Even though there is no Package.swift file in this project in the main branch, the project is now SPM-compatible,
with support for a dynamic and a static version of the package (only the dynamic target works via SPM for now;
last tested w/ Xcode 12.2).

*⚠️ Important*: If you use the static version of the package, you *must* add the `-ObjC` flag in _Other Linker Flags_
(`OTHER_LDFLAGS`) in the build settings of your project.

Regarding the static version of the SPM project not working, I suspect an Xcode bug: the build system tries
and embed the `.a` lib in the app and fails when signing. +
You can use the static xcframework directly though (download it in the releases section of the project on GitHub).

Compatibility is provided via an `xcframework` only. Source SPM-compatibility cannot be provided
AFAICT because the project has a part which does not use ARC, and has a custom modulemap.

Carthage installation should work too for dynamic frameworks, but it hasn’t been tested.

== Versioning Note
The pbxproj sets `DYLIB_CURRENT_VERSION` and `DYLIB_COMPATIBILITY_VERSION` to `$(MARKETING_VERSION)`.
We set the same versions in both fields because this lib is not meant to be shared between processes,
so we don’t really care about the versions.

== Notes About the Documentation

I tried having a proper inline documentation.
It was not trivial because the project is in Objective-C.

I used http://www.cocoanutsdev.com/resources/headerdoc-reference-by-justin-loew[a quick HeaderDoc reference] I found, which does not describe HeaderDoc per se
(e.g. `headerdoc2html` fails to recognize a lot of tags), but gave me the tags I needed to have a proper render in Xcode.

I tried to build the HTML documentation with `appledoc`.
It does not know more about the `@c` tag than `headerdoc2html` sadly.

There is still a lot of work to be done to have something fully good.

== Credits
This project was originally created by {frizlab}[François Lamboley] while working at {happn}[happn].
